spring.application.name=safetyalert

# Database URL, Username, aur Password
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Database settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Debugging enable
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.engine.jdbc.env.internal=DEBUG